spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
    kafka:
        bootstrap-servers: 172.25.131.138:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
    port: 8080